name: ESP32 Build and Flash

on:
  push:

jobs:
  build_and_flash:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4

      - name: Load ESP-IDF
        run: |
          source ~/esp-idf/export.sh
          idf.py --version

      - name: Detect serial port
        run: |
          PORT=$(ls /dev/ttyACM* /dev/ttyUSB* 2>/dev/null | head -n 1)

          if [ -z "$PORT" ]; then
            echo "ESP32 serial port not found!"
            ls /dev/tty*
            exit 1
          fi

          echo "Detected port: $PORT"
          echo "PORT=$PORT" >> $GITHUB_ENV

      - name: Build firmware
        run: |
          source ~/esp-idf/export.sh
          idf.py set-target esp32c3
          idf.py build

      - name: Flash firmware
        run: |
          source ~/esp-idf/export.sh
          idf.py -p $PORT flash

      - name: Capture UART log
        run: |
          stty -F $PORT 115200
          timeout 10s cat $PORT > log.txt || true
          cat log.txt
