name: ESP32 Build and Flash

on:
  push:

jobs:
  build_and_flash:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4

      - name: Load ESP-IDF
        run: |
          source ~/esp-idf/export.sh
          idf.py --version

      - name: Build
        run: |
          source ~/esp-idf/export.sh
          idf.py set-target esp32c3
          idf.py build
    
      - name: flash && Monitor
        run: |
          idf.py -p /dev/ttyACM0 flash 
          idf.py monitor
